name: Rust

on:
  push:
    branches:
    - 'master'

  pull_request:
    branches:
    - 'master'

  merge_group:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      with:
        components: clippy

    - name: Print rustc version
      run: rustc --version

    - name: Print cargo-clippy version
      run: cargo clippy --version

    - name: Run cargo-clippy checks
      run: cargo clippy --all-targets --workspace -- -Dwarnings

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      with:
        components: rustfmt

    - name: Print rustc version
      run: rustc --version

    - name: Print cargo-fmt version
      run: cargo fmt --version

    - name: Run cargo-fmt checks
      run: cargo fmt --all --check

  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1

    - name: Print rustc version
      run: rustc --version

    - name: Run cargo-test checks
      run: cargo test --verbose --all-targets --workspace

  cargo-test-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1

    - name: Print rustc version
      run: rustc --version

    - name: Run cargo-test-doc checks
      run: cargo test --verbose --doc --workspace

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1

    - name: Setup cargo-deny
      uses: taiki-e/install-action@9d97868af30d08d0e1292c7fc0b1bcfc2c372c86 # cargo-deny

    - name: Print cargo-deny version
      run: cargo deny --version

    - name: Run cargo-deny checks
      run: cargo deny check

  cargo-machete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1

    - name: Setup cargo-machete
      uses: taiki-e/install-action@54f2112bcbf044548e86ae160bed0769bc3a76b2 # cargo-machete

    - name: Print cargo-machete version
      run: cargo machete --version

    - name: Run cargo-machete checks
      run: cargo machete

  rust-workflow-status:
    needs: ["cargo-clippy", "cargo-fmt", "cargo-test", "cargo-deny", "cargo-machete"]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check workflow status
      run: |
        return_code=0

        if [[ "${{ needs.cargo-clippy.result }}" == "failure" ]]; then
          echo "cargo-clippy job failed"
          return_code=1
        fi

        if [[ "${{ needs.cargo-fmt.result }}" == "failure" ]]; then
          echo "cargo-fmt job failed"
          return_code=1
        fi

        if [[ "${{ needs.cargo-test.result }}" == "failure" ]]; then
          echo "cargo-test job failed"
          return_code=1
        fi

        if [[ "${{ needs.cargo-test-doc.result }}" == "failure" ]]; then
          echo "cargo-test-doc job failed"
          return_code=1
        fi

        if [[ "${{ needs.cargo-deny.result }}" == "failure" ]]; then
          echo "cargo-deny job failed"
          return_code=1
        fi

        if [[ "${{ needs.cargo-machete.result }}" == "failure" ]]; then
          echo "cargo-machete job failed"
          return_code=1
        fi

        if [[ $return_code -ne 0 ]]; then
          exit $return_code
        fi

        echo "All jobs succeeded"

